# Generated by Django 3.1.7 on 2021-03-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210313_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='categories',
        ),
    ]
