# Generated by Django 3.1.7 on 2021-04-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordered',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='ordered',
            name='orderitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
