# Generated by Django 3.1.7 on 2021-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_ordered_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stock']},
        ),
        migrations.AddField(
            model_name='product',
            name='amazon',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
